---
- name: config | Ensuring Guacamole Folders Exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ guacamole_tomcat_user }}"
    group: "{{ guacamole_tomcat_user }}"
    mode: u=rwx,g=rx,o=rx
  become: true
  with_items:
    - /etc/guacamole
    - /etc/guacamole/lib
    - /etc/guacamole/extensions

- name: config | Configuring guacd
  ansible.builtin.template:
    src: guacd.conf.j2
    dest: /etc/guacamole/guacd.conf
    owner: "{{ guacamole_tomcat_user }}"
    group: "{{ guacamole_tomcat_user }}"
    mode: u=rw,g=r,o=r
  become: true
  notify:
    - kill guacd
    - restart guacd
  when: guacd_config.install

- name: config | Configuring guacamole.properties
  ansible.builtin.template:
    src: guacamole.properties.j2
    dest: /etc/guacamole/guacamole.properties
    owner: "{{ guacamole_tomcat_user }}"
    group: "{{ guacamole_tomcat_user }}"
    mode: u=rw,g=r,o=r
  become: true
  notify:
    - "restart {{ guacamole_tomcat_service }}"
    - kill guacd
    - restart guacd

- name: config | Configuring user-mapping.xml
  ansible.builtin.template:
    src: user-mapping.xml.j2
    dest: /etc/guacamole/user-mapping.xml
    owner: "{{ guacamole_tomcat_user }}"
    group: "{{ guacamole_tomcat_user }}"
    mode: u=rw,g=r,o=r
  become: true
  notify:
    - "restart {{ guacamole_tomcat_service }}"
    - kill guacd
    - restart guacd
  when: guacamole_users is defined and guacamole_users | list | length >= 1

- name: config | list previous extensions version
  ansible.builtin.find:
    paths: "/etc/guacamole/extensions/"
    excludes: '*{{ guacamole_version }}*'
    file_type: file
  register: guacamole_previous_extensions

- name: config | Delete previous extensions version
  ansible.builtin.file:
    path: "{{ guacamole_extensions.path }}"
    state: absent
  loop: "{{ guacamole_previous_extensions.files }}"
  loop_control:
    loop_var: guacamole_extensions

- name: config | Creating Tomcat symlink For guacamole.properties
  ansible.builtin.file:
    src: /etc/guacamole
    dest: "{{ '/usr/share/' + guacamole_tomcat + '/.guacamole' }}"
    state: link
    owner: "{{ guacamole_tomcat_user }}"
    group: "{{ guacamole_tomcat_user }}"
  become: true
  notify:
    - "restart {{ guacamole_tomcat_service }}"
    - kill guacd
    - restart guacd
